import type { Description } from '~/components/component-description.vue';
import { SIZES } from '~/constants';

export { SIZES };

export const DESCRIPTIONS: Description[] = [
    {
        name: 'table',
        props: [
            {
                name: 'size',
                type: 'Size',
                default: 'md',
                values: SIZES,
            },
            {
                name: 'zebra',
                type: 'boolean',
                description: 'Whether the table should have zebra striping',
            },
            {
                name: 'pin-rows',
                type: 'boolean',
                description: 'Whether the table should pin rows',
            },
            {
                name: 'pin-cols',
                type: 'boolean',
                description: 'Whether the table should pin columns',
            },
        ],
        slots: [
            {
                name: 'default',
                description: 'Content of the table',
            },
        ],
    },
];

// SAMPLE DATA

export const records = [
    {
        id: 1,
        name: 'Cy Ganderton',
        job: 'Quality Control Specialist',
        favoriteColor: 'Blue',
    },
    {
        id: 2,
        name: 'Hart Hagerty',
        job: 'Desktop Support Technician',
        favoriteColor: 'Purple',
    },
    {
        id: 3,
        name: 'Brice Swyre',
        job: 'Tax Accountant',
        favoriteColor: 'Red',
    },
];

export const recordsWithVisuals = [
    {
        name: 'Hart Hagerty',
        country: 'United States',
        job: 'Desktop Support Technician',
        company: 'Zemlak, Daniel and Leannon',
        favoriteColor: 'Purple',
    },
    {
        name: 'Brice Swyre',
        country: 'China',
        job: 'Tax Accountant',
        company: 'Carroll Group',
        favoriteColor: 'Red',
    },
    {
        name: 'Marjy Ferencz',
        country: 'Russia',
        job: 'Ofice Assistant I',
        company: 'Rowe-Schoen',
        favoriteColor: 'Crimson',
    },
    {
        name: 'Yancy Tear',
        country: 'Brazil',
        job: 'Community Outreach Specialist',
        company: 'Wyman-Ledner',
        favoriteColor: 'indigo',
    },
];

export const recordsXs = [
    {
        id: 1,
        name: 'Cy Ganderton',
        job: 'Quality Control Specialist',
        company: 'Littel, Schaden and Vandervort',
        location: 'Canada',
        lastLogin: '12/16/2020',
        favoriteColor: 'Blue',
    },
    {
        id: 2,
        name: 'Hart Hagerty',
        job: 'Desktop Support Technician',
        company: 'Zemlak, Daniel and Leannon',
        location: 'United States',
        lastLogin: '12/5/2020',
        favoriteColor: 'Purple',
    },
    {
        id: 3,
        name: 'Brice Swyre',
        job: 'Tax Accountant',
        company: 'Carroll Group',
        location: 'China',
        lastLogin: '8/15/2020',
        favoriteColor: 'Red',
    },
    {
        id: 4,
        name: 'Marjy Ferencz',
        job: 'Office Assistant I',
        company: 'Rowe-Schoen',
        location: 'Russia',
        lastLogin: '3/25/2021',
        favoriteColor: 'Crimson',
    },
    {
        id: 5,
        name: 'Yancy Tear',
        job: 'Community Outreach Specialist',
        company: 'Wyman-Ledner',
        location: 'Brazil',
        lastLogin: '5/22/2020',
        favoriteColor: 'Indigo',
    },
    {
        id: 6,
        name: 'Irma Vasilik',
        job: 'Editor',
        company: 'Wiza, Bins and Emard',
        location: 'Venezuela',
        lastLogin: '12/8/2020',
        favoriteColor: 'Purple',
    },
    {
        id: 7,
        name: 'Meghann Durtnal',
        job: 'Staff Accountant IV',
        company: 'Schuster-Schimmel',
        location: 'Philippines',
        lastLogin: '2/17/2021',
        favoriteColor: 'Yellow',
    },
    {
        id: 8,
        name: 'Sammy Seston',
        job: 'Accountant I',
        company: "O'Hara, Welch and Keebler",
        location: 'Indonesia',
        lastLogin: '5/23/2020',
        favoriteColor: 'Crimson',
    },
    {
        id: 9,
        name: 'Lesya Tinham',
        job: 'Safety Technician IV',
        company: 'Turner-Kuhlman',
        location: 'Philippines',
        lastLogin: '2/21/2021',
        favoriteColor: 'Maroon',
    },
    {
        id: 10,
        name: 'Zaneta Tewkesbury',
        job: 'VP Marketing',
        company: 'Sauer LLC',
        location: 'Chad',
        lastLogin: '6/23/2020',
        favoriteColor: 'Green',
    },
    {
        id: 11,
        name: 'Andy Tipple',
        job: 'Librarian',
        company: 'Hilpert Group',
        location: 'Poland',
        lastLogin: '7/9/2020',
        favoriteColor: 'Indigo',
    },
    {
        id: 12,
        name: 'Sophi Biles',
        job: 'Recruiting Manager',
        company: 'Gutmann Inc',
        location: 'Indonesia',
        lastLogin: '2/12/2021',
        favoriteColor: 'Maroon',
    },
    {
        id: 13,
        name: 'Florida Garces',
        job: 'Web Developer IV',
        company: 'Gaylord, Pacocha and Baumbach',
        location: 'Poland',
        lastLogin: '5/31/2020',
        favoriteColor: 'Purple',
    },
    {
        id: 14,
        name: 'Maribeth Popping',
        job: 'Analyst Programmer',
        company: 'Deckow-Pouros',
        location: 'Portugal',
        lastLogin: '4/27/2021',
        favoriteColor: 'Aquamarine',
    },
    {
        id: 15,
        name: 'Moritz Dryburgh',
        job: 'Dental Hygienist',
        company: 'Schiller, Cole and Hackett',
        location: 'Sri Lanka',
        lastLogin: '8/8/2020',
        favoriteColor: 'Crimson',
    },
    {
        id: 16,
        name: 'Reid Semiras',
        job: 'Teacher',
        company: 'Sporer, Sipes and Rogahn',
        location: 'Poland',
        lastLogin: '7/30/2020',
        favoriteColor: 'Green',
    },
    {
        id: 17,
        name: 'Alec Lethby',
        job: 'Teacher',
        company: 'Reichel, Glover and Hamill',
        location: 'China',
        lastLogin: '2/28/2021',
        favoriteColor: 'Khaki',
    },
    {
        id: 18,
        name: 'Aland Wilber',
        job: 'Quality Control Specialist',
        company: 'Kshlerin, Rogahn and Swaniawski',
        location: 'Czech Republic',
        lastLogin: '9/29/2020',
        favoriteColor: 'Purple',
    },
    {
        id: 19,
        name: 'Teddie Duerden',
        job: 'Staff Accountant III',
        company: 'Pouros, Ullrich and Windler',
        location: 'France',
        lastLogin: '10/27/2020',
        favoriteColor: 'Aquamarine',
    },
    {
        id: 20,
        name: 'Lorelei Blackstone',
        job: 'Data Coordiator',
        company: 'Witting, Kutch and Greenfelder',
        location: 'Kazakhstan',
        lastLogin: '6/3/2020',
        favoriteColor: 'Red',
    },
];

export const pinnedRows = {
    A: ['Ant-Man', 'Aquaman', 'Asterix', 'The Atom', 'The Avengers'],
    B: ['Batgirl', 'Batman', 'Batwoman', 'Black Canary', 'Black Panther'],
    C: ['Captain America', 'Captain Marvel', 'Catwoman', 'Conan the Barbarian'],
    D: ['Daredevil', 'The Defenders', 'Doc Savage', 'Doctor Strange'],
    E: ['Elektra'],
    F: ['Fantastic Four'],
    G: [
        'Ghost Rider',
        'Green Arrow',
        'Green Lantern',
        'Guardians of the Galaxy',
    ],
    H: ['Hawkeye', 'Hellboy', 'Incredible Hulk'],
    I: ['Iron Fist', 'Iron Man'],
    M: ['Marvelman'],
    R: ['Robin', 'The Rocketeer'],
    S: ['The Shadow', 'Spider-Man', 'Sub-Mariner', 'Supergirl', 'Superman'],
    T: ['Teenage Mutant Ninja Turtles', 'Thor'],
    W: ['The Wasp', 'Watchmen', 'Wolverine', 'Wonder Woman'],
    X: ['X-Men'],
    Z: ['Zatanna', 'Zatara'],
};
